LIGHT = {
    "background": "#FFFFFF",
    "foreground": "#1E1E1E",
    "current_line": "#F3F3F3",
    "line_number_bg": "#F8F8F8",
    "line_number_fg": "#A0A0A0",
    "line_number_fg_current": "#333333",
    "selection_bg": "#ADD6FF",
    "bracket_match_bg": "#FFD700",
    "keyword": ("#0000FF", True, False),
    "function": ("#795E26", False, False),
    "class_": ("#267F99", True, False),
    "builtin": ("#267F99", False, False),
    "decorator": ("#267F99", False, False),
    "string": ("#A31515", False, False),
    "comment": ("#008000", False, True),
    "number": ("#098658", False, False),
    "operator": ("#000000", False, False),
}

DARK = {
    "background": "#1E1E1E",
    "foreground": "#D4D4D4",
    "current_line": "#2A2D2E",
    "line_number_bg": "#1E1E1E",
    "line_number_fg": "#6E7681",
    "line_number_fg_current": "#C6C6C6",
    "selection_bg": "#264F78",
    "bracket_match_bg": "#646400",
    "keyword": ("#569CD6", True, False),
    "function": ("#DCDCAA", False, False),
    "class_": ("#4EC9B0", True, False),
    "builtin": ("#4FC1FF", False, False),
    "decorator": ("#4FC1FF", False, False),
    "string": ("#CE9178", False, False),
    "comment": ("#6A9955", False, True),
    "number": ("#B5CEA8", False, False),
    "operator": ("#D4D4D4", False, False),
}

_COMMON_VARS = {
    "menu_selection_fg": "#FFFFFF",
    "statusbar_bg": "#007ACC",
    "statusbar_fg": "#FFFFFF",
    "tree_selection_fg": "#FFFFFF",
    "close_hover_fg": "#FFFFFF",
    "completer_selection_fg": "#FFFFFF",
    "terminal_bg": "#1E1E1E",
    "terminal_fg": "#CCCCCC",
    "terminal_prompt_fg": "#6A9955",
}

LIGHT_VARS = {
    "bg_main": "#F3F3F3",
    "bg_menu": "#F0F0F0",
    "bg_input": "#FFFFFF",
    "fg": "#333333",
    "fg_dim": "#666666",
    "fg_title": "#555555",
    "border": "#D4D4D4",
    "border_input": "#C8C8C8",
    "accent": "#0078D4",
    "accent_bg": "#CCE8FF",
    "hover": "#D6D6D6",
    "hover_input": "#E9E9E9",
    "pressed": "#C4C4C4",
    "scrollbar": "#C1C1C1",
    "scrollbar_hover": "#A0A0A0",
    "output_fg": "#1E1E1E",
    "placeholder_fg": "#999999",
    "disabled": "#AAAAAA",
    "activity_bg": "#2C2C2C",
    "activity_border": "#3C3C3C",
    "activity_fg": "#888888",
    "activity_hover_bg": "#3C3C3C",
    "activity_hover_fg": "#CCCCCC",
    "activity_checked_fg": "#FFFFFF",
    "close_hover": "#C14545",
    "selection_bg": "#ADD6FF",
    **_COMMON_VARS,
}

DARK_VARS = {
    "bg_main": "#1E1E1E",
    "bg_menu": "#2D2D2D",
    "bg_input": "#3C3C3C",
    "fg": "#CCCCCC",
    "fg_dim": "#777777",
    "fg_title": "#AAAAAA",
    "border": "#3C3C3C",
    "border_input": "#555555",
    "accent": "#0078D4",
    "accent_bg": "#094771",
    "hover": "#3C3C3C",
    "hover_input": "#505050",
    "pressed": "#505050",
    "scrollbar": "#555555",
    "scrollbar_hover": "#777777",
    "output_fg": "#CCCCCC",
    "placeholder_fg": "#666666",
    "disabled": "#5A5A5A",
    "activity_bg": "#333333",
    "activity_border": "#3C3C3C",
    "activity_fg": "#666666",
    "activity_hover_bg": "#3C3C3C",
    "activity_hover_fg": "#CCCCCC",
    "activity_checked_fg": "#FFFFFF",
    "close_hover": "#C14545",
    "selection_bg": "#264F78",
    **_COMMON_VARS,
}

SELECTION_BG = {
    "light": "#ADD6FF",
    "dark": "#264F78",
}
